// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"wenxinhexuan/controllers"
	"wenxinhexuan/dao"
	"wenxinhexuan/routes"
	"wenxinhexuan/service"
)

// Injectors from wire.go:

func InitApp() App {
	userDAOInterface := dao.NewUserDAO()
	userServiceInterface := service.NewUserService(userDAOInterface)
	userController := controllers.NewUserController(userServiceInterface)
	songDAOInterface := dao.NewSongDAO()
	songServiceInterface := service.NewSongService(songDAOInterface)
	songController := controllers.NewSongController(songServiceInterface)
	engine := routes.RegisterRoutes(userController, songController)
	app := NewApp(engine)
	return app
}
