# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\"1\n\x0fGenerateRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\x12\r\n\x05topic\x18\x02 \x01(\t\"$\n\x10GenerateResponse\x12\x10\n\x08response\x18\x01 \x01(\t2C\n\x08Generate\x12\x37\n\x0eGenerateStream\x12\x10.GenerateRequest\x1a\x11.GenerateResponse0\x01\x42\rZ\x0b./grpc,grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013./grpc,grpc'
  _globals['_GENERATEREQUEST']._serialized_start=13
  _globals['_GENERATEREQUEST']._serialized_end=62
  _globals['_GENERATERESPONSE']._serialized_start=64
  _globals['_GENERATERESPONSE']._serialized_end=100
  _globals['_GENERATE']._serialized_start=102
  _globals['_GENERATE']._serialized_end=169
# @@protoc_insertion_point(module_scope)
